### ISSUE TITLE
app suggestion

### ISSUE THREAD

**Issue by fallsdevil** [you-apps/you-apps.github.io#2]
Hello, I really like the **You Apps** projects, so if it's not too much trouble, I would like to suggest an app that would be interesting, if possible, a client email app to unify all email accounts in a single app, something simple, but with the nice interface.

I know there are some apps available, but the interface gets confusing, and I think your style of apps makes it easier to use.

And I'm sorry you're making this suggestion here, but I couldn't find it anywhere else and I found it inconvenient to do this in one of the repositories of other apps that are unrelated.

**Comment by kamlendras** [comment]
We have matrix room for that https://matrix.to/#/#you-apps:matrix.org
